// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLXFTM0iI--dKakSox1qc2Ml0HZg2q00Y',
    appId: '1:288666490162:web:17335f8212c69e2c40332b',
    messagingSenderId: '288666490162',
    projectId: 'todo-3-cdada',
    authDomain: 'todo-3-cdada.firebaseapp.com',
    storageBucket: 'todo-3-cdada.appspot.com',
    measurementId: 'G-K9NS2W0BG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA51qqw7JfdkWRm4dC1DoVdMIrqrNjRwSo',
    appId: '1:288666490162:android:4a3dd207e03ee4cc40332b',
    messagingSenderId: '288666490162',
    projectId: 'todo-3-cdada',
    storageBucket: 'todo-3-cdada.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAI4hULHRkSCmkW_VirYmRKbmAg7NVbpI',
    appId: '1:288666490162:ios:d3e4b506487b123a40332b',
    messagingSenderId: '288666490162',
    projectId: 'todo-3-cdada',
    storageBucket: 'todo-3-cdada.appspot.com',
    iosBundleId: 'com.example.todoList3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAI4hULHRkSCmkW_VirYmRKbmAg7NVbpI',
    appId: '1:288666490162:ios:d3e4b506487b123a40332b',
    messagingSenderId: '288666490162',
    projectId: 'todo-3-cdada',
    storageBucket: 'todo-3-cdada.appspot.com',
    iosBundleId: 'com.example.todoList3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLXFTM0iI--dKakSox1qc2Ml0HZg2q00Y',
    appId: '1:288666490162:web:e696494cd374274040332b',
    messagingSenderId: '288666490162',
    projectId: 'todo-3-cdada',
    authDomain: 'todo-3-cdada.firebaseapp.com',
    storageBucket: 'todo-3-cdada.appspot.com',
    measurementId: 'G-84J280Q3ZH',
  );
}
